### ISSUE TITLE
"Use netcat" appears

### ISSUE THREAD

**Issue by runn1ng** [solusipse/fiche#31] opened 2015-12-06 11:41 UTC
For some reason, when I am running one specific command, instead of the URL, I see just

`Use netcat.`

at the terminal. I am already using netcat. What am I doing wrong?

**Comment by jeaye** [comment] 2015-12-13 13:53
I've seen this when fiche is malconfigured; it was always fixable on my end.

**Comment by Fil** [comment] 2015-12-13 14:22
I have the same problem just now from a "olinux brique" (ARM Debian):

```
echo just testing! | nc solusipse.net 9999
Use netcat.
```

the same command works well from a Mac and from a x86 Debian.


```
root@olinux:~# uname -a
Linux olinux 4.2.0-1-armmp #1 SMP Debian 4.2.6-1 (2015-11-10) armv7l GNU/Linux
```

**Comment by jeaye** [comment] 2015-12-13 14:24
Double check the configuration of the server; you have something wrong.

**Comment by jeaye** [comment] 2015-12-13 14:25
Here's a reference to my server's fiche setup: https://github.com/jeaye/nix-files/blob/master/service/fiche.nix

**Comment by runn1ng** [comment] 2015-12-13 14:27
Hm. I am using termbin.com as a server.

**Comment by Fil** [comment] 2015-12-13 14:27
as you can see I'm using solusipse.net as a server , from various machines as clients

**Comment by jeaye** [comment] 2015-12-13 14:31
I see. You'll get that error if [this](https://github.com/solusipse/fiche/blob/master/fiche.c#L370) returns 0.

**Comment by jeaye** [comment] 2015-12-15 13:44
After some more exploration, and seeing this issue again, I've found a client-side solution. My script used to look like (given some paste site foo.com):

```bash
#!/bin/bash
nc foo.com 9999
```

Using certain commands, like `find . -name '*png' | paste`, I'd get `Use netcat.` every time. I found that this is because `find` is still streaming into `paste` and fiche doesn't like that. I've fixed this issue by changing my script to do this:

```bash
#!/bin/bash

file=$(mktemp)
cat >> $file
nc foo.com 9999 < $file
rm -f $file
```

@Fil, @runn1ng, I hope this works for you.

**Comment by Fil** [comment] 2015-12-15 13:48
nope :(

```
ifconfig > /tmp/xxxx && nc solusipse.net 9999 < /tmp/xxxx
Use netcat.
```

**Comment by runn1ng** [comment] 2015-12-15 13:54
It works for me. But I don't want to close if it doesn't work for everyone

**Comment by solusipse** [comment] 2015-12-15 16:10
Thank you. Could you check with service I launched on port `9998`?
E.g. `echo test | nc termbin.com 9998`. I reverted some changes, I'm suspect they cause some problems.

**Comment by Fil** [comment] 2015-12-15 17:43
it's a bit random but most of the time NOK with a text of a few lines, and OK with just one line

```
root@olinux:~#   echo test | nc termbin.com 9998
http://termbin.com/vrxo
root@olinux:~#   echo test | nc termbin.com 9998
http://termbin.com/sqxw
root@olinux:~# ifconfig  | nc termbin.com 9998
Use netcat.
root@olinux:~# ifconfig  | nc termbin.com 9998
Use netcat.
root@olinux:~# ifconfig > /tmp/xxxx ; cat /tmp/xxxx | nc termbin.com 9998
Use netcat.
root@olinux:~# ifconfig > /tmp/xxxx ; cat /tmp/xxxx | nc termbin.com 9998
Use netcat.
root@olinux:~# ifconfig > /tmp/xxxx ; cat /tmp/xxxx | nc termbin.com 9998
Use netcat.
root@olinux:~# echo test | nc termbin.com 9998
http://termbin.com/smvt
root@olinux:~# echo test | nc termbin.com 9998
http://termbin.com/6e38
root@olinux:~# echo test | nc termbin.com 9998
http://termbin.com/wgxc
root@olinux:~# ifconfig > /tmp/xxxx ; cat /tmp/xxxx | nc termbin.com 9998
Use netcat.
root@olinux:~# nc termbin.com 9998 < /tmp/xxxx
http://termbin.com/6nsf
root@olinux:~# nc termbin.com 9998 < /tmp/xxxx
Use netcat.
root@olinux:~# nc termbin.com 9998 < /tmp/xxxx
Use netcat.
root@olinux:~# nc termbin.com 9998 < /tmp/xxxx
Use netcat.
root@olinux:~# echo test | nc termbin.com 9998
http://termbin.com/mmn2
root@olinux:~# nc termbin.com 9998 < /tmp/xxxx
Use netcat.
root@olinux:~# cat /tmp/xxxx| nc termbin.com 9998 
Use netcat.
root@olinux:~# cat /tmp/xxxx| nc termbin.com 9998 
Use netcat.
```

**Comment by solusipse** [comment] 2015-12-15 20:20
That's strange. I guess we can't do anything about it. Please use some modern netcat implementation, for example [ncat](https://nmap.org/ncat/)

**Comment by solusipse** [comment] 2015-12-16 15:15
Btw, could you please provide more information on your netcat version?

**Comment by Fil** [comment] 2015-12-16 15:40
I am using debian on a very small ARM computer that is described on http://labriqueinter.net/

```
root@olinux:~# uname -a
Linux olinux 4.2.0-1-armmp #1 SMP Debian 4.2.6-1 (2015-11-10) armv7l GNU/Linux
root@olinux:~# nc -h
[v1.10-41]
connect to somewhere:	nc [-options] hostname port[s] [ports] ... 
listen for inbound:	nc -l -p port [-options] [hostname] [port]
options:
	-c shell commands	as `-e'; use /bin/sh to exec [dangerous!!]
	-e filename		program to exec after connect [dangerous!!]
	-b			allow broadcasts
	-g gateway		source-routing hop point[s], up to 8
	-G num			source-routing pointer: 4, 8, 12, ...
	-h			this cruft
	-i secs			delay interval for lines sent, ports scanned
        -k                      set keepalive option on socket
	-l			listen mode, for inbound connects
	-n			numeric-only IP addresses, no DNS
	-o file			hex dump of traffic
	-p port			local port number
	-r			randomize local and remote ports
	-q secs			quit after EOF on stdin and delay of secs
	-s addr			local source address
	-T tos			set Type Of Service
	-t			answer TELNET negotiation
	-u			UDP mode
	-v			verbose [use twice to be more verbose]
	-w secs			timeout for connects and final net reads
	-C			Send CRLF as line-ending
	-z			zero-I/O mode [used for scanning]
port numbers can be individual or ranges: lo-hi [inclusive];
hyphens in port names must be backslash escaped (e.g. 'ftp\-data').
```

**Comment by jeaye** [comment] 2015-12-16 17:03
On Wed, Dec 16, 2015 at 07:15:16AM -0800, solusipse wrote:
>    Btw, could you please provide more information on your netcat version?

I see this also with GNU netcat 0.7.1-5 (latest Arch Linux), so it's not
about not being up to date.

**Comment by solusipse** [comment] 2015-12-16 22:46
I guess it is, maybe it's latest in Arch Linux repo, but take a look at their website: http://netcat.sourceforge.net/.
```
Current Version: Netcat 0.7.1
Released on: 11 Jan 2004
````
And `1.10` is 8 years old. Nevertheless, I'd like to investigate that and make fiche compatibile with these. Thanks.

**Comment by jeaye** [comment] 2015-12-17 00:51
> I guess it is, maybe it's latest in Arch Linux repo, but take a look at their website: http://netcat.sourceforge.net/.
> 
>    Current Version: Netcat 0.7.1
>    Released on: 11 Jan 2004

Ok, you realize I said:

> GNU netcat 0.7.1-5 (latest Arch Linux)

Which means **it is the latest**.

**Comment by jeaye** [comment] 2015-12-17 01:05
1.10 is not GNU netcat, it's OpenBSD netcat, which is currently on 1.105_7-7. The stable release is 8 years old, yeah, but does netcat really change much (sincerely asking -- I don't see why it would)?

**Comment by jeaye** [comment] 2015-12-22 06:50
Unfortunately, I've found that even the script I shared above doesn't always work. It's sporadic, but sometimes fiche just says "Use netcat." If I run the same command again, multiple times, it might end up accepting one of them, though nothing has changed on my end.

If fiche is picky about something, that's understandable. It not being consistent is a serious issue.

**Comment by solusipse** [comment] 2016-01-07 16:04
Sorry for late reply, I was a bit busy recently. Thanks for your work. That's very strange since it works correctly on my Arch Linux (with same netcat version). I'm afraid, I cannot reproduce this issue for now, I need some more time or more clues where to look for solution. For only last month, 3500 pastes were posted successfully. I assume this is rather related to some network limitations (strange firewall settings or something? I got no clue). Have you tried installing fiche on your own machine? Does it work as expected on localhost?

**Comment by sbrl** [comment] 2016-01-07 19:37
Weirdly, I fixed my 'issue' by simply issuing the netcat command again, or switching from `nc` to `netcat` or vice versa. No idea why that worked.

**Comment by jeaye** [comment] 2016-01-07 23:24
On Thu, Jan 07, 2016 at 11:37:32AM -0800, Starbeamrainbowlabs wrote:
>    Weirdly, I fixed my 'issue' by simply issuing the netcat command again, or
>    switching from nc to netcat or vice versa. No idea why that worked.

Before assuming so, keep trying with various commands, including those
above. The issue is intermittent, so the nc/netcat commands will often
work.

**Comment by jeaye** [comment] 2016-01-07 23:45
On Thu, Jan 07, 2016 at 08:04:10AM -0800, solusipse wrote:
>    Sorry for late reply, I was a bit busy recently. Thanks for your work.
>    That's very strange since it works correctly on my Arch Linux (with same
>    netcat version). I'm afraid, I cannot reproduce this issue for now, I need
>    some more time or more clues where to look for solution. For only last
>    month, 3500 pastes were posted successfully. I assume this is rather
>    related to some network limitations (strange firewall settings or
>    something? I got no clue). Have you tried installing fiche on your own
>    machine? Does it work as expected on localhost?

The better number is now many people fiche told 'Use netcat.' to last
month. As mentioned, fiche ends up working _some of the time_.

When you tested locally, on Arch, which commands did you run and how
many times did you run them? I've just tested the following script on
both my site running fiche and termbin.com; they both exhibit the issue.

```bash
for i in {1..100}; do ip a | nc termbin.com 9999 2>&1; sleep 1; done | tee output
```

Feel free to remove the sleep, if you'd like. My test for the above is
shown here: http://dpaste.com/0WFAMWB After 100 calls, there were 6
occurrences of the issue. Please run this script, on your machine, and
let me know what you see. If you'd like, you can _also_ (but please do
try termbin) try pastespace.org, which is my instance of fiche.

**Comment by sbrl** [comment] 2016-01-21 16:53
@jeaye Since nobody else has, here's my output:

http://dpaste.com/0TQJWWD

The only thing I changed was `nc` -> `netcat`. I didn't actually get a single successful hit.

**Comment by solusipse** [comment] 2016-01-22 19:04
Once again, sorry for delay in replying. I managed to reproduce this problem and, as I suspected, it was probably related to this commit https://github.com/solusipse/fiche/commit/49ea4c7ccd736ed5cc42b7cb0075a5feebf2ca25 and issue #14. I reverted this one. @jeaye, @sbrl could you, please, check if it works now?

**Comment by jeaye** [comment] 2016-01-23 01:42
@solusipse It looks like every request is succeeding now, but they do take noticeably longer: 5.6 seconds for each one, on my end, using the GNU netcat in Arch Linux. Seems like that's exactly what you were looking to avoid in #14.

**Comment by jeaye** [comment] 2016-01-23 01:51
Interestingly, if I use bsd-netcat, from the Arch repos it takes only 0.6 seconds (removes the 5 second delay mentioned in #14). So the long delay shows up for me with GNU netcat. Also, the "Use netcat" issue now isn't reproducible with either GNU netcat or BSD netcat. We can reopen #14, if you'd like, and consider this one solved (once you merge it into master).

**Comment by sbrl** [comment] 2016-01-23 10:01
I've done a git pull, and then I recompiled with make. I restarted the systemd service I have in place (options: `/srv/fiche/fiche -u fiche -d starbeamrainbowlabs.com/bin -o /srv/www/bin -B 131072 -b /srv/fiche/fiche-bans.txt -l /srv/fiche/fiche-access.log`). It works sometimes now, but not all the time.

If I run a for loop in bash with a sleep, it never works. If I enter the command manually, it sometimes works (~1 time in 3).

**Comment by jeaye** [comment] 2016-01-23 10:02
@sbrl He didn't update master; just termbin.com

**Comment by sbrl** [comment] 2016-01-23 10:04
@jeaye Right. termbin.com works flawlessly everytime. Also, I got 1 5 letter url out of 100 attempts, the rest were 4 letters long. Intentional?

**Comment by solusipse** [comment] 2016-01-23 10:55
>@sbrl He didn't update master; just termbin.com
@sbrl. Thank you. That's right, just wanted to be sure that this will solve the problem. It's already updated: abf8ae5.
>Also, I got 1 5 letter url out of 100 attempts, the rest were 4 letters long. Intentional?
Yup, it happens when it generates directory name that already exists.

@jeaye Thank you. I guess we can't really fix it. Maybe we should make a list of preferred implementations? As you suggested, I'm closing this one now and I'll reopen #14. Thanks for your help.

**Closed by solusipse** 2016-01-23 10:55 UTC

**Comment by sbrl** [comment] 2016-01-23 10:58
@solusipse Yep, that commit fixes it.

I think a list of preferred implementations (or command line arguments for implementations) is a good idea.

**Comment by Fil** [comment] 2016-01-23 11:37
works for me too!

**Comment by solusipse** [comment] 2016-01-23 11:38
@sbrl, @Fil great, thanks!
